// <auto-generated />
using System;
using GoldenWhistle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GoldenWhistle.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708153826_addmarketplaceandpubmodels")]
    partial class addmarketplaceandpubmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GoldenWhistle.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("GoldenWhistle.Models.BracketPick", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsScored")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUpset")
                        .HasColumnType("bit");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("PointsAwarded")
                        .HasColumnType("int");

                    b.Property<string>("PredictedAnytimeScorerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PredictedAwayScore")
                        .HasColumnType("int");

                    b.Property<long?>("PredictedBetterPossessionTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("PredictedFirstScorerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PredictedHigherXgTeamId")
                        .HasColumnType("bigint");

                    b.Property<int?>("PredictedHomeScore")
                        .HasColumnType("int");

                    b.Property<string>("PredictedLastScorerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredictedManOfTheMatchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredictedMostAssistsPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PredictedMostCornersTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("PredictedMostDistancePlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PredictedMostFoulsPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PredictedMostFoulsTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("PredictedMostPassesPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PredictedMostPassesTeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PredictedMostRedsTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("PredictedMostSavesGoalkeeperName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PredictedMostSavesTeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("PredictedMostYellowsTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("PredictedOutcome")
                        .HasColumnType("int");

                    b.Property<bool>("PredictedOwnGoal")
                        .HasColumnType("bit");

                    b.Property<long?>("PredictedOwnGoalTeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("BracketPicks");
                });

            modelBuilder.Entity("GoldenWhistle.Models.JerseyListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SellerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("SellerRating")
                        .HasColumnType("float");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("JerseyListings");
                });

            modelBuilder.Entity("GoldenWhistle.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ApiLeagueId")
                        .HasColumnType("bigint");

                    b.Property<string>("ColorHex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("GoldenWhistle.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ApiMatchId")
                        .HasColumnType("bigint");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("Cancelled")
                        .HasColumnType("bit");

                    b.Property<bool>("Finished")
                        .HasColumnType("bit");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("KickoffUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<bool>("Started")
                        .HasColumnType("bit");

                    b.Property<string>("StatusLong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusShort")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("GoldenWhistle.Models.MatchStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayAerialDuelsWon")
                        .HasColumnType("int");

                    b.Property<int?>("AwayCorners")
                        .HasColumnType("int");

                    b.Property<double?>("AwayDistanceCoveredKm")
                        .HasColumnType("float");

                    b.Property<int?>("AwayDuelsWon")
                        .HasColumnType("int");

                    b.Property<int?>("AwayFouls")
                        .HasColumnType("int");

                    b.Property<int?>("AwayFreeKicks")
                        .HasColumnType("int");

                    b.Property<int?>("AwayInterceptions")
                        .HasColumnType("int");

                    b.Property<int?>("AwayOffsides")
                        .HasColumnType("int");

                    b.Property<double?>("AwayPassAccuracyPct")
                        .HasColumnType("float");

                    b.Property<int?>("AwayPasses")
                        .HasColumnType("int");

                    b.Property<int?>("AwayPenalties")
                        .HasColumnType("int");

                    b.Property<double?>("AwayPossessionPct")
                        .HasColumnType("float");

                    b.Property<int?>("AwayRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("AwaySaves")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("AwayShotsTotal")
                        .HasColumnType("int");

                    b.Property<int?>("AwayTackles")
                        .HasColumnType("int");

                    b.Property<double?>("AwayXg")
                        .HasColumnType("float");

                    b.Property<int?>("AwayYellowCards")
                        .HasColumnType("int");

                    b.Property<long?>("BetterPossessionTeamId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("FetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstScorerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoalScorerNamesRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("HigherXgTeamId")
                        .HasColumnType("bigint");

                    b.Property<int?>("HomeAerialDuelsWon")
                        .HasColumnType("int");

                    b.Property<int?>("HomeCorners")
                        .HasColumnType("int");

                    b.Property<double?>("HomeDistanceCoveredKm")
                        .HasColumnType("float");

                    b.Property<int?>("HomeDuelsWon")
                        .HasColumnType("int");

                    b.Property<int?>("HomeFouls")
                        .HasColumnType("int");

                    b.Property<int?>("HomeFreeKicks")
                        .HasColumnType("int");

                    b.Property<int?>("HomeInterceptions")
                        .HasColumnType("int");

                    b.Property<int?>("HomeOffsides")
                        .HasColumnType("int");

                    b.Property<double?>("HomePassAccuracyPct")
                        .HasColumnType("float");

                    b.Property<int?>("HomePasses")
                        .HasColumnType("int");

                    b.Property<int?>("HomePenalties")
                        .HasColumnType("int");

                    b.Property<double?>("HomePossessionPct")
                        .HasColumnType("float");

                    b.Property<int?>("HomeRedCards")
                        .HasColumnType("int");

                    b.Property<int?>("HomeSaves")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsOnTarget")
                        .HasColumnType("int");

                    b.Property<int?>("HomeShotsTotal")
                        .HasColumnType("int");

                    b.Property<int?>("HomeTackles")
                        .HasColumnType("int");

                    b.Property<double?>("HomeXg")
                        .HasColumnType("float");

                    b.Property<int?>("HomeYellowCards")
                        .HasColumnType("int");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("LastScorerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManOfTheMatchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("ManOfTheMatchTeamId")
                        .HasColumnType("bigint");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("MostAssistsCount")
                        .HasColumnType("int");

                    b.Property<string>("MostAssistsPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MostCornersTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("MostDistancePlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MostFoulsPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MostFoulsTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("MostPassesPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MostPassesTeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MostRedsTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("MostSavesGoalkeeperName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MostSavesTeamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("MostYellowsTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnGoalScorerNamesRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("MatchStats");
                });

            modelBuilder.Entity("GoldenWhistle.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("ListingId")
                        .HasColumnType("int");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("GoldenWhistle.Models.MoodVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int>("Mood")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("VotedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("MoodVotes");
                });

            modelBuilder.Entity("GoldenWhistle.Models.PubLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FreeEntry")
                        .HasColumnType("bit");

                    b.Property<bool>("HdScreens")
                        .HasColumnType("bit");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Reviews")
                        .HasColumnType("int");

                    b.Property<int>("Screens")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PubLocations");
                });

            modelBuilder.Entity("GoldenWhistle.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("ApiTeamId")
                        .HasColumnType("bigint");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrimaryLeagueId")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryLeagueId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("LeagueMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrivateLeagueId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PrivateLeagueId");

                    b.HasIndex("UserId");

                    b.ToTable("LeagueMembers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PrivateLeague", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("PrivateLeagues");
                });

            modelBuilder.Entity("GoldenWhistle.Models.BracketPick", b =>
                {
                    b.HasOne("GoldenWhistle.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenWhistle.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoldenWhistle.Models.JerseyListing", b =>
                {
                    b.HasOne("GoldenWhistle.Models.ApplicationUser", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("GoldenWhistle.Models.Match", b =>
                {
                    b.HasOne("GoldenWhistle.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenWhistle.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GoldenWhistle.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("GoldenWhistle.Models.MatchStats", b =>
                {
                    b.HasOne("GoldenWhistle.Models.Match", "Match")
                        .WithOne()
                        .HasForeignKey("GoldenWhistle.Models.MatchStats", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("GoldenWhistle.Models.Message", b =>
                {
                    b.HasOne("GoldenWhistle.Models.JerseyListing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenWhistle.Models.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("GoldenWhistle.Models.MoodVote", b =>
                {
                    b.HasOne("GoldenWhistle.Models.Match", "Match")
                        .WithMany("MoodVotes")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenWhistle.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GoldenWhistle.Models.Team", b =>
                {
                    b.HasOne("GoldenWhistle.Models.League", "PrimaryLeague")
                        .WithMany("Teams")
                        .HasForeignKey("PrimaryLeagueId");

                    b.Navigation("PrimaryLeague");
                });

            modelBuilder.Entity("LeagueMember", b =>
                {
                    b.HasOne("PrivateLeague", "League")
                        .WithMany("Members")
                        .HasForeignKey("PrivateLeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenWhistle.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GoldenWhistle.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GoldenWhistle.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GoldenWhistle.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GoldenWhistle.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrivateLeague", b =>
                {
                    b.HasOne("GoldenWhistle.Models.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("GoldenWhistle.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GoldenWhistle.Models.Match", b =>
                {
                    b.Navigation("MoodVotes");
                });

            modelBuilder.Entity("PrivateLeague", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
